/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstudandoParaProva;

import java.util.ArrayList;
import java.util.List;


public class App {

    public static void main(String[] args) {
        
         System.out.println("-------------------------------------------------------------------------\n");
        
        System.out.println("**VETORES E MATRIZES**\n");
        
        int[] vetor = new int[5];

        // Inicializando o vetor
        vetor[0] = 10;
        vetor[1] = 20;
        vetor[2] = 30;
        vetor[3] = 40;
        vetor[4] = 50;

        // Acessando elementos do vetor
        System.out.println("VETOR: Elemento no índice 2: " + vetor[2] + "\n"); // Saída: Elemento no índice 2: 30
        
        
         int[][] matriz = new int[3][2];

        // Inicializando a matriz
        matriz[0][0] = 1;
        matriz[0][1] = 2;
        matriz[1][0] = 3;
        matriz[1][1] = 4;
        matriz[2][0] = 5;
        matriz[2][1] = 6;

        // Acessando elementos da matriz
        System.out.println("MATRIZ: Elemento na posição (1, 1): " + matriz[1][1] + "\n"); // Saída: Elemento na posição (1, 1): 4
        
        System.out.println("-------------------------------------------------------------------------\n");
        
        System.out.println("**ENUMS**\n");
        
        
        enum DiaSemana {
            DOMINGO,
            SEGUNDA,
            TERCA,
            QUARTA,
            QUINTA,
            SEXTA,
            SABADO
        }
        
        DiaSemana hoje = DiaSemana.SABADO;

        // Exemplo de uso do Enum em um switch-case
        switch (hoje) {
            case DOMINGO:
                System.out.println("Hoje é domingo.");
                break;
            case SEGUNDA:
                System.out.println("Hoje é segunda-feira.");
                break;
            case QUARTA:
                System.out.println("Hoje é quarta-feira.");
                break;
            // ... outros casos ...
            default:
                System.out.println("Hoje é um dia da semana diferente.");
        
        
    
        }
        
        
         System.out.println("-------------------------------------------------------------------------\n");
        
        System.out.println("**COLLECTIONS**\n");
        
         List<String> lista = new ArrayList<>();

        // Adicionando elementos à lista
        lista.add("Maçã");
        lista.add("Banana");
        lista.add("Laranja");

        // Acessando elementos da lista
        System.out.println("Elemento no índice 1: " + lista.get(1)); // Saída: Elemento no índice 1: Banana

        // Iterando sobre os elementos da lista
        for (String fruta : lista) {
            System.out.println(fruta);
        }
        
        
        System.out.println("-------------------------------------------------------------------------\n");
        
        System.out.println("**CLASSES WRAPPER**\n");
        
        /**int numeroInteiro = 42;
        Integer objetoInteiro = Integer.valueOf(numeroInteiro);

        // Usando a classe Double para converter double em Double
        double numeroDouble = 3.14;
        Double objetoDouble = Double.valueOf(numeroDouble);

        // Usando a classe Boolean para converter boolean em Boolean
        boolean valorBooleano = true;
        Boolean objetoBooleano = Boolean.valueOf(valorBooleano);

        // Usando a classe Character para converter char em Character
        char caractere = 'A';
        Character objetoCaractere = Character.valueOf(caractere);
        
          **/
        
        //System.out.println("**AUTOBOXING\n");
        
        int numeroInteiro = 42;

        // Autoboxing: convertendo int em Integer automaticamente
        Integer objetoInteiro = numeroInteiro;

        // Autoboxing ao passar um argumento para um método que espera um objeto Integer
        imprimirNumero(objetoInteiro);
        
         //System.out.println("**UNBOXING**\n");
        
        Integer objetoInt = 10;

        // Unboxing: convertendo Integer em int automaticamente
        int numeroInt = objetoInt;

        // Unboxing ao passar um argumento para um método que espera um tipo primitivo int
        somarNumeros(numeroInt, 5);
        
        }
    

        public static void imprimirNumero(Integer numero) {
            System.out.println("**AUTOBOXING\n");
            System.out.println("Número: " + numero);
        }
        
        public static void somarNumeros(int a, int b) {
            int resultado = a + b;
            System.out.println("\n**UNBOXING**\n");
            System.out.println("Resultado: " + resultado);
    }
        
        
        
        
    }
         
         

