/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import model.Project;
import controller.ProjectController;
import controller.TaskController;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import model.Task;

public class App {
    

    public static void main(String[] args) throws SQLException {
       
    ProjectController projectController = new ProjectController();
//        
//        Project project = new Project();
//        project.setName("Projeto");
//        project.setDescription("projeto teste");
//        
//        projectController.save(project);
        
        //--------------------------------------------------------------------
//        Project project = new Project();
//        project.setId(5);
//        project.setName("ALteração");
//        project.setDescription("alteração no id 5");
//       
//        
//        projectController.update(project);
//        
        //--------------------------------------------------------------------
//         projectController.removeById(4);
        
        
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos: " + projects.size());
       
       //--------------------------------------------------------------------
       
       TaskController taskController = new TaskController();
       
        Task task = new Task();
        
      //--------------------------------------------------------------------
     
//       task.setIdProject(2);
//       task.setName("Tarefa 1");
//       task.setDescription("Tarefa 1");
//       task.setIsCompleted(false);
//       task.setNotes("Sem notas");
//       task.setDeadline(new Date());
//       
//       taskController.save(task);
      
       //--------------------------------------------------------------------
       
//       task.setId(3);
//       task.setIdProject(2);
//       task.setName("Tarefa 2");
//       task.setDescription("Tarefa 2");
//       task.setIsCompleted(true);
//       task.setNotes("Sem notas");
//       task.setDeadline(new Date());
//       
//       taskController.update(task);
       
       //--------------------------------------------------------------------
       
      //taskController.removeById(2);
       
//        List<Task> tasks = taskController.getByProjectId(2);
//        System.out.println("Total de tarefas: " + tasks.size());
    }
    
    
    
  

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
